spring.application.name=nexus-backend
spring.datasource.url=jdbc:h2:mem:nexusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# JWT Configuration (simulated for simplicity)
nexus.jwt.secret=9a67471ec639f0567f81439c05656545b3528b3297a9354006c04f997f805a9d
nexus.jwt.expiration=86400000
