spring.datasource.url=jdbc:mysql://db:3306/nexusdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=nexususer
spring.datasource.password=nexuspass
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.h2.console.enabled=false

# JWT Configuration
nexus.jwt.secret=9a67471ec639f0567f81439c05656545b3528b3297a9354006c04f997f805a9d
nexus.jwt.expiration=86400000
