# PROD (Main) Environment Properties
# In a real scenario, these would be injected via environment variables for security
spring.datasource.url=jdbc:mysql://${DB_HOST:db}:3306/nexusdb?useSSL=false
spring.datasource.username=${DB_USERNAME:nexususer}
spring.datasource.password=${DB_PASSWORD:nexuspass}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
nexus.jwt.secret=${JWT_SECRET:prod_secret_key_very_long_and_secure_67471ec639f0567f81439c0565}
nexus.jwt.expiration=3600000
