# UAT Environment Properties
spring.datasource.url=jdbc:mysql://db:3306/nexus_uat?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=uat_user
spring.datasource.password=uat_pass
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
nexus.jwt.secret=uat_secret_key_b3528b3297a9354006c04f997f805a9d9a67471ec639f056
nexus.jwt.expiration=43200000
